name: Build and Release

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, pdo_mysql
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install PHP deps
        run: |
          composer install \
            --no-dev \
            --optimize-autoloader \
            --no-interaction

      - name: Build frontend assets
        run: |
          npm ci
          npm run build

      - name: Prepare Laravel caches
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan optimize

      - name: Create release branch
        run: git checkout -B release

      - name: Commit build artifacts
        run: |
          git add -f vendor public/build bootstrap/cache
          git commit -m "Build release $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes"

      - name: Tag and push
        run: |
          VERSION="v$(date +'%Y.%m.%d.%H%M')"
          git tag -f "$VERSION"
          git push origin release --tags --force

      - name: Run remote commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: pomellorancheshoa.com
          username: serfcnte
          key: ${{ secrets.CPANEL_SSH_KEY }}
          script: |
            (
              cd pomellorancheshoa
              git fetch --all
              git reset --hard origin/release
              php /opt/cpanel/composer/bin/composer install --no-dev -q
            ) < /dev/null
            kill -9 $SSH_AGENT_PID || true
            exit 0
